export const CLOTHING_DONATION_CENTERS = [
  {
    id: 1,
    name: "Goodwill Calgary",
    lat: 51.0564,
    lng: -114.1059,
    address: "5010 17 Ave SE, Calgary, AB T2A 0W4",
    hours: {
      Monday: "9 AM - 5 PM",
      Tuesday: "9 AM - 5 PM",
      Wednesday: "9 AM - 5 PM",
      Thursday: "9 AM - 5 PM",
      Friday: "9 AM - 5 PM",
      Saturday: "9 AM - 5 PM",
      Sunday: "Closed",
    },
  },
  {
    id: 2,
    name: "Salvation Army Thrift Store",
    lat: 51.0497,
    lng: -114.0854,
    address: "1212 12 Ave SW, Calgary, AB T3C 0P1",
    hours: {
      Monday: "9 AM - 6 PM",
      Tuesday: "9 AM - 6 PM",
      Wednesday: "9 AM - 6 PM",
      Thursday: "9 AM - 6 PM",
      Friday: "9 AM - 6 PM",
      Saturday: "9 AM - 5 PM",
      Sunday: "Closed",
    },
  },
  {
    id: 3,
    name: "Value Village Calgary",
    lat: 51.053,
    lng: -114.1072,
    address: "4610 17 Ave SE, Calgary, AB T2A 0W9",
    hours: {
      Monday: "9 AM - 9 PM",
      Tuesday: "9 AM - 9 PM",
      Wednesday: "9 AM - 9 PM",
      Thursday: "9 AM - 9 PM",
      Friday: "9 AM - 9 PM",
      Saturday: "9 AM - 9 PM",
      Sunday: "10 AM - 6 PM",
    },
  },
  {
    id: 4,
    name: "The Kidney Foundation Thrift Store",
    lat: 51.0391,
    lng: -114.071,
    address: "3805 14 St NW, Calgary, AB T2K 1N7",
    hours: {
      Monday: "9 AM - 5 PM",
      Tuesday: "9 AM - 5 PM",
      Wednesday: "9 AM - 5 PM",
      Thursday: "9 AM - 5 PM",
      Friday: "9 AM - 5 PM",
      Saturday: "10 AM - 4 PM",
      Sunday: "Closed",
    },
  },
  {
    id: 5,
    name: "Mission Thrift Store",
    lat: 51.0389,
    lng: -114.0738,
    address: "201, 4000 4 St NW, Calgary, AB T2K 1A5",
    hours: {
      Monday: "10 AM - 6 PM",
      Tuesday: "10 AM - 6 PM",
      Wednesday: "10 AM - 6 PM",
      Thursday: "10 AM - 6 PM",
      Friday: "10 AM - 6 PM",
      Saturday: "10 AM - 5 PM",
      Sunday: "Closed",
    },
  },
];
